# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("club", "0002_order_session")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
