# Generated by Django 6.1.1 on 2026-09-09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("club", "0003_order_name")]

    operations = [
        migrations.RemoveField(model_name="product", name="cost"),
        migrations.RemoveField(model_name="orderitem", name="unit_cost"),
    ]
