# Generated by Django 6.1.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("club", "0004_remove_product_cost_and_order_item_unit_cost")]

    operations = [
        migrations.AddField(
            model_name="playingsession",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
