# Generated by Django 6.1.1 on 2026-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_playingsession_paused_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playingsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='active', max_length=12),
        ),
    ]
